import {RootState} from 'types';

export const getAssetPairs = (state: RootState) => state.assetPairs;
export const getAuthentication = (state: RootState) => state.authentication;
export const getChartData = (state: RootState) => state.chartData;
export const getComments = (state: RootState) => state.comments;
export const getCurrencies = (state: RootState) => state.currencies;
export const getExchangeOrders = (state: RootState) => state.exchangeOrders;
export const getFollowers = (state: RootState) => state.followers;
export const getFollowings = (state: RootState) => state.followings;
export const getInvitationLimits = (state: RootState) => state.invitationLimits;
export const getInvitations = (state: RootState) => state.invitations;
export const getManager = (state: RootState) => state.manager;
export const getMints = (state: RootState) => state.mints;
export const getNotifications = (state: RootState) => state.notifications.notifications || {};
export const hasMoreNotifications = (state: RootState) => state.notifications.hasMore;
export const isLoadingNotifications = (state: RootState) => state.notifications.isLoading;
export const getTotalUnreadNotificationCount = (state: RootState) => state.notifications.totalUnreadCount;
export const getPosts = (state: RootState) => state.posts.posts;
export const getSelf = (state: RootState) => state.self;
export const getTrades = (state: RootState) => state.trades;
export const getUserStats = (state: RootState) => state.userStats;
export const getUsers = (state: RootState) => state.users;
export const getWallets = (state: RootState) => state.wallets;
export const getWires = (state: RootState) => state.wires;
export const hasMorePosts = (state: RootState) => state.posts.hasMore;
export const isLoadingPosts = (state: RootState) => state.posts.isLoading;
